"""Copy every apiai.me script verbatim to docs/scripts/ and generate docs/scripts/CATALOG.md.

Andreas decided (2026-09-29) that all scripts may be kept verbatim; see docs/HANDOVER.md.
Each script is written exactly as exported (source_code), under a filename-safe name.
The catalog shows which API runs each script and how it compares to the repo's scripts/.

Sources: docs/export/*.sanitized.json (tracked); docs/crawl/admin/api/*usage.json (optional).
Usage: python3 docs/tools/build_scripts_catalog.py
"""
import json
import re
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1]
REPO = DOCS.parent
OUT = DOCS / "scripts"


def filename(name):
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower() + ".py"


def usage_by_slug():
    f = next((DOCS / "crawl/admin/api").glob("*_admin_api_usage.json"), None)
    if not f:
        return {}
    return {u["workflow_slug"]: u["total_requests"] for u in json.loads(f.read_text())["response"]["by_workflow"]}


def repo_sources():
    return {p.stem: p.read_text().strip() for p in (REPO / "scripts").glob("*.py")}


def repo_match(name, source, repo):
    """Repo file with identical code (any name), or None."""
    if repo.get(name) == source.strip():
        return name
    return next((n for n, code in repo.items() if code == source.strip()), None)


def repo_status(name, source, repo):
    match = repo_match(name, source, repo)
    if match == name:
        return "samma som `scripts/`"
    if match:
        return f"samma som `scripts/{match}.py` (annat namn)"
    if name in repo:
        return "**skiljer** från `scripts/`"
    return "bara på sajten"


def main():
    export = json.loads(next((DOCS / "export").glob("*.sanitized.json")).read_text())
    uses = usage_by_slug()
    repo = repo_sources()
    apis_by_script = {}
    for w in export["workflows"]:
        script = (w.get("workflow_json") or {}).get("script")
        if script:
            apis_by_script.setdefault(script, []).append(w)

    OUT.mkdir(exist_ok=True)
    rows = []
    for s in sorted(export["scripts"], key=lambda s: s["name"].lower()):
        fname = filename(s["name"])
        (OUT / fname).write_text(s["source_code"].rstrip() + "\n")
        apis = apis_by_script.get(s["name"], [])
        api_cell = "<br>".join(f"`{w['slug']}`" + (f" ({uses[w['slug']]})" if uses.get(w["slug"]) else "")
                               for w in apis) or "—"
        rows.append(f"| [`{s['name']}`]({fname}) | {(s.get('description') or '').strip()} | "
                    f"{s.get('requirements') or '—'} | {api_cell} | {repo_status(s['name'], s['source_code'], repo)} |")

    matched = {repo_match(s["name"], s["source_code"], repo) for s in export["scripts"]}
    only_repo = sorted(n for n in repo if n not in matched and n not in {s["name"] for s in export["scripts"]})
    lines = [
        "<!-- GENERATED by docs/tools/build_scripts_catalog.py — do not edit by hand. -->",
        "",
        "# Scriptkatalog: alla script på apiai.me",
        "",
        f"{len(rows)} script, exporterade 2026-09-29 och sparade **ordagrant** i den här mappen. "
        "Kontraktet för hur ett script skrivs: `../NODE_CONTRACT.md` och "
        "`guidelines/SCRIPT_GUIDELINES.md`.",
        "",
        "*API (anrop 30 d)* = API:t som kör scriptet, med antal anrop 2026-08-31 – 2026-09-29 "
        "om det fanns några. *Repo* = jämfört med `scripts/` i detta repo.",
        "",
        "| Script | Beskrivning | Paket | API (anrop 30 d) | Repo |",
        "|---|---|---|---|---|",
        *rows,
        "",
        "## Bara i repot, inte på sajten",
        "",
        *(f"- `scripts/{n}.py`" for n in only_repo),
        "",
    ]
    (OUT / "CATALOG.md").write_text("\n".join(lines))
    print(f"Wrote {len(rows)} scripts + CATALOG.md to {OUT}; only in repo: {only_repo}")


if __name__ == "__main__":
    main()
