"""Generate docs/models/CATALOG.md: one entry per model-backed API on apiai.me.

Sources (local):
- docs/export/*.sanitized.json         params incl. allowed values (tracked in git)
- docs/crawl/admin/api/*workflows.json  category, ai_context, probe status (gitignored)
- docs/crawl/admin/api/*usage.json      requests per API, last 30 days (gitignored)

Usage: python3 docs/tools/build_models_catalog.py
"""
import json
from collections import defaultdict
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1]
CRAWL = DOCS / "crawl/admin/api"
OUT = DOCS / "models/CATALOG.md"
SERVER_ORDER = ["gemini", "openai", "xai", "replicate"]


def load_crawl(suffix):
    return json.loads(next(CRAWL.glob(f"*{suffix}.json")).read_text())["response"]


def price(v):
    return "gratis" if not v else f"${v:g}"


def param_line(p):
    bits = [f"`{p['name']}`"]
    if p.get("default_value") not in (None, ""):
        bits.append(f"default `{p['default_value']}`")
    if p.get("allowed_values"):
        bits.append("värden: " + ", ".join(f"`{a}`" for a in p["allowed_values"]))
    if p.get("required"):
        bits.append("**obligatorisk**")
    desc = (p.get("description") or "").strip()
    return "- " + " · ".join(bits) + (f" — {desc}" if desc else "")


def main():
    export = json.loads(next((DOCS / "export").glob("*.sanitized.json")).read_text())
    export_by_slug = {w["slug"]: w for w in export["workflows"]}
    usage = load_crawl("_admin_api_usage")
    requests = {u["workflow_slug"]: u for u in usage["by_workflow"]}
    wfs = [w for w in load_crawl("_admin_api_workflows") if "script" not in (w["workflow_json"] or {})]

    groups = defaultdict(list)
    for w in wfs:
        groups[w["server_type"]].append(w)

    lines = [
        "<!-- GENERATED by docs/tools/build_models_catalog.py — do not edit by hand. -->",
        "",
        "# Modellkatalog: alla modell-API:er på apiai.me",
        "",
        f"Genererad ur admin-data 2026-09-29. {len(wfs)} API:er som anropar en extern modell "
        "(script-API:er finns i `NODE_CONTRACT.md`). Översikt och lärdomar: `../MODELS.md`.",
        "",
        f"*Anrop 30 d* = anrop {usage['from']} – {usage['to']}. *AI context* är plattformens egen "
        "vägledning till hjälpchatten, ordagrant (ofta AI-genererad via *Suggest*; kontrollera "
        "påståenden om modeller innan de används).",
        "",
        "## Översikt",
        "",
        "| Provider | API | Modell | Pris/anrop | In → Ut | Anrop 30 d | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    ordered = [w for s in SERVER_ORDER for w in sorted(groups.get(s, []), key=lambda w: (w["category"] or "", w["name"]))]
    for w in ordered:
        j = w["workflow_json"]
        u = requests.get(w["slug"], {})
        status = "inaktiv" if not w["active"] else (w.get("last_probe_status") or "ej testad")
        io = f"{'+'.join(w.get('accepted_inputs') or [])} → {'+'.join(w.get('output_types') or [])}"
        lines.append(f"| {w['server_type']} | [{w['name']}](#{w['slug']}) | `{j.get('model')}` | "
                     f"{price(w['price_per_request'])} | {io} | {u.get('total_requests', 0)} | {status} |")

    for server in SERVER_ORDER:
        if not groups.get(server):
            continue
        lines += ["", f"## {server}"]
        for w in sorted(groups[server], key=lambda w: (w["category"] or "", w["name"])):
            j = dict(w["workflow_json"])
            model = j.pop("model", None)
            lines += ["", f'<a id="{w["slug"]}"></a>', f"### {w['name']}", ""]
            lines.append(f"- **Slug:** `{w['slug']}` · **Modell:** `{model}` · **Kategori:** {w['category'] or '—'}")
            lines.append(f"- **Pris:** {price(w['price_per_request'])} per anrop · "
                         f"**Max bilder in:** {w.get('max_images')} · **Aktiv:** {'ja' if w['active'] else 'nej'}")
            if w.get("description"):
                lines.append(f"- **Beskrivning:** {w['description'].strip()}")
            if j:
                lines += ["- **Konfiguration** (`workflow_json`, utom modell):", "", "  ```json",
                          *("  " + l for l in json.dumps(j, indent=2, ensure_ascii=False).splitlines()),
                          "  ```"]
            params = export_by_slug.get(w["slug"], {}).get("params") or []
            if params:
                lines += ["", "**Parametrar:**", ""] + [param_line(p) for p in params]
            if w.get("ai_context"):
                lines += ["", "**AI context:**", ""] + ["> " + l if l else ">" for l in w["ai_context"].strip().splitlines()]

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT} ({len(wfs)} APIs, {len(lines)} lines)")


if __name__ == "__main__":
    main()
